### ISSUE TITLE
swiftmailer.delivery_addresses configuration?

### ISSUE THREAD

**Issue by TrogWarZ** [tehplague/swiftmailer-mailgun-bundle#37]
```yaml
cspoo_swiftmailer_mailgun:
    key    : 'key-somekey'
    domain : 'sandboxsomedomain.mailgun.org'

swiftmailer:
    transport: 'mailgun'
    spool:     { type: memory } # This will start sending emails on kernel.terminate event
    delivery_addresses:
        - 'testing@example.com'
```

```php
$message = \Swift_Message::newInstance();
$message->setFrom('from@example.com');
$message->setSubject('subj');
$message->setTo('to@example.com');
$message->setBody('some html body', 'text/html', 'utf-8');
```

With default transport it works good – sends email to `testing@example.com` (from configuration).

But with mailgun transport it send email to `to@example.com` which is incorrect.

Is it implemented but i'm using it wrong? Or, if not, how it can be workarounded?
