### ISSUE TITLE
Multi key and domain

### ISSUE THREAD

**Issue by fyher** [tehplague/swiftmailer-mailgun-bundle#38]
How I can use , if I want multi domain and key ? 

thanks

**Comment by Nyholm** [comment]
I do not think that is supported. That should be an excellent feature.

**Comment by fyher** [comment]
it 's possible to move the api key to the file config in param in the mailer class ?

**Comment by Nyholm** [comment]
I'm not too sure what you mean. 

I think we should allow config like:

```Yaml
Mailgun:
  foo:
    Key: xx
    Domain: xx
  Bar:
    Key: yay
    Domain: yay
```

**Comment by fyher** [comment]
why not.But this don't working actually ?

**Comment by stevechilds** [comment]
Can't believe this hasn't been implemented, this is actually a show stopper for us. Our CRM platform hosts multiple sites from the same setup, we need the ability to support multiple domains.

*sigh* time to have a dig around in the code.

**Comment by tehplague** [comment]
Mailgun itself does in fact support multiple domains per account. If they are managed in the same account it should perfectly be possible to use them.

**Comment by stevechilds** [comment]
Actually, there's a very simple solution - subclass the Transport class! Symfony allows you to specify any service as a transport in the config, doing this allows you to inject other dependencies into the transport constructor, allowing you to change the domain passed through to the underlying Mailgun Transport.

If anyone is interested...

Step 1, create a custom class - I saved this into src/<Bundle>/SwiftMailer 

```
<?php

namespace foo\WebsiteBundle\SwiftMailer;

use cspoo\Swiftmailer\MailgunBundle\Service\MailgunTransport;
use Mailgun\Mailgun;
use Symfony\Component\DependencyInjection\ContainerInterface;


class customMailgunTransport extends MailgunTransport
{
    public function __construct(ContainerInterface $container, \Swift_Events_EventDispatcher $eventDispatcher, Mailgun $mailgun, $domain)
    {
        parent::__construct($eventDispatcher, $mailgun, $domain);

    }
}

```

Then create the new service entry in services.yml...

```
    # Custom SwiftMailer Mailgun Transport - gets credentials from site config.
    swiftmailer.mailer.transport.custom_mailgun:
              class: foo\WebsiteBundle\SwiftMailer\customMailgunTransport
              arguments: [@service_container,'@mailgun.swift_transport.eventdispatcher','@mailgun.library','mydomain.com']

```
Alter the mail config - in our case we want the mailgun transport to be manually selected in the code...
(in config_global.yml) - I can't recall if this is a stock Symfony file or not, it may just be config.yml
```
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: %mailer_transport%
            host:      %mailer_host%
            username:  %mailer_user%
            password:  %mailer_password%
        mailgun:
            transport: engage_mailgun

```

Then when you want to send via mailgun, you create it with a call like: 

`$swiftmailer` = $this->getContainer()->get('swiftmailer.mailer.mailgun');

The service name is swiftmailer.mailer. and then the mailer name from the config.yml file.

HTH....
