### ISSUE TITLE
Had to use substantially different config to get this bundle working.

### ISSUE THREAD

**Issue by henrypenny** [tehplague/swiftmailer-mailgun-bundle#43]
Here's the config I needed to get this working:

Using Guzzle5 adaptor.

```
swiftmailer:
    transport: %mailer_transport%
    spool:     { type: memory }

cspoo_swiftmailer_mailgun:
    key: "%mailer_mailgun_key%"
    domain: "%mailer_mailgun_domain%"

services:
    mailgun.library:
        class: Mailgun\Mailgun
        public: true
        arguments: ["%mailer_mailgun_key%", '@guzzle5.adpater']
        calls:
          - ['setApiVersion', ['v3']]

    guzzle5.adpater:
        class: 'Http\Adapter\Guzzle5\Client'
        arguments: ['@guzzle5.client']

    guzzle5.client:
        class: GuzzleHttp\Client
        arguments: [{'base_url':'https://api.mailgun.net', {'defaults' : {'auth' : ['api', '%mailer_mailgun_key%']}}}]
```
This is quite different to the docs, so I'm wondering where I went wrong.
