### ISSUE TITLE
The child node "key" at path "cspoo_swiftmailer_mailgun" must be configured.

### ISSUE THREAD

**Issue by nmobregon** [tehplague/swiftmailer-mailgun-bundle#71]
Hi! I installed everything and Im getting this error whenever I want to run a command.

I'm running Symfony 4 and this version of the lib
**"name": "cspoo/swiftmailer-mailgun-bundle",
"version": "1.1.0",**

`$ php bin/console doctrine:schema:update`

> In ArrayNode.php line 230:
> 
>   The child node "key" at path "cspoo_swiftmailer_mailgun" must be configured.

I can't configure as it shows in the docs because it changes for Symfony v4, so I tried putting this conf in config/services.yaml, config/packages/mailgun.yaml, I even created a parameters.yaml but with no success.

```
    cspoo_swiftmailer_mailgun:
        key: "key-f132131313131"
        domain: "sandbox700asdasdasdadasdasdasdadada.mailgun.org"
    swiftmailer:
        transport: "mailgun"
```

HELP PLEASE!!
Thanks in advance
