### ISSUE TITLE
Transport not registered exception

### ISSUE THREAD

**Issue by RageZBla** [tehplague/swiftmailer-mailgun-bundle#72]
We tried as per documentation and symfony is exploding when trying to send email. It says that the "mailgun" transport is not a default transport. 

To make it work we had to add the following service definition:

```yaml
services:
  # Hijack the transport because of mailgun
  swiftmailer.mailer.default.transport:
    alias: mailgun.swift_transport.transport
```

Is that expected or something is missing from the documentation?
