### ISSUE TITLE
How to configure this bundle in Symfony 4?

### ISSUE THREAD

**Issue by Jeeppler** [tehplague/swiftmailer-mailgun-bundle#74]
Could you provide some information in the `README.md` on how to configure this bundle in Symfony 4?

Until now I run into the same issue as others have:
- [The child node "key" at path "cspoo_swiftmailer_mailgun" must be configured.](https://github.com/tehplague/swiftmailer-mailgun-bundle/issues/71)
- [Symfony 4 issue MailgunTransporter not set](https://github.com/tehplague/swiftmailer-mailgun-bundle/issues/70)

However, I think the easiest solution for most of those problems would probably be to add an example configuration for Symfony 4 in the `README.md`.

**Comment by fluchi** [comment]
Hi @Jeeppler,
Setting up this on Symfony 4 is slight different.

1. Add you Mailgun credentials on .env.dist (add the same lines on .env, just in case)
```
MAILGUN_DOMAIN=<your domain>
MAILGUN_API_KEY=<your key>
MAILGUN_SENDER=<your sender>

```

2. Adding on AppKernel, now config/bundles.php
`cspoo\Swiftmailer\MailgunBundle\cspooSwiftmailerMailgunBundle::class => ['all' => true],`

3. Configuring credentials: 
Create a new config file on config/packages/mailgun.yaml (if it's not there) and copy the following lines:
```
cspoo_swiftmailer_mailgun:
    key: '%env(MAILGUN_API_KEY)%'
    domain: "%env(MAILGUN_DOMAIN)%"

services:
    Mailgun\Mailgun:
        class: Mailgun\Mailgun
        factory: ['Mailgun\Mailgun', create]
        arguments: ['%env(MAILGUN_API_KEY)%']
```

4. Add the following line on config/packages/swiftmailer:
```
swiftmailer:
    # url: '%env(MAILER_URL)%'
    transport: 'mailgun'
    spool: { type: 'memory' }
```
p.s.: Not sure if you really have to comment url

5. Test your setup with the following command on your terminal:
`bin/console swiftmailer:email:send --from=<from email> --to=<to email> --subject="Foo" --body="Bar"`

With this setup, I've made it work.
Let me know if I miss something on it.

Felipe
